import type { WorkflowEdgeData, WorkflowNodeData, WorkflowNodeKind } from "./types"

const flows: Record<string, { title: string; description: string; steps: [string, string, WorkflowNodeKind][] }> = {
  "ai-customer-support": { title: "From repeated questions to faster customer replies", description: "A support journey that answers from approved content and keeps people in control.", steps: [["Customer inbox", "Website chat, WhatsApp or email", "input"], ["Intent check", "FAQ, order, booking, complaint or person", "decision"], ["Approved answers", "Search current support content", "knowledge"], ["Clear reply", "Answer common questions plainly", "assistant"], ["Human handoff", "Route sensitive or unclear requests", "human"], ["Ticket summary", "Create a ticket with useful context", "output"], ["Support trends", "Show recurring questions", "dashboard"]] },
  "ai-sales-lead-follow-up": { title: "From new lead to booked conversation", description: "Respond while interest is fresh, qualify consistently and give sales a clean next action.", steps: [["New lead", "Form, ad, WhatsApp, email or CRM", "trigger"], ["Quick reply", "Acknowledge the inquiry", "assistant"], ["Qualification", "Ask fit, timing and interest questions", "decision"], ["Lead score", "Prioritise fit, urgency and intent", "knowledge"], ["Booking", "Offer a call, visit or demo", "integration"], ["CRM update", "Save answers and next action", "output"], ["Sales handoff", "Send a concise lead brief", "human"]] },
  "ai-knowledge-assistant": { title: "From scattered documents to clear internal answers", description: "Turn approved internal material into answers with visible sources and an improvement loop.", steps: [["Document library", "SOPs, policies, PDFs and FAQs", "trigger"], ["Knowledge index", "Organise approved information", "knowledge"], ["Team question", "Ask in everyday language", "input"], ["Relevant sources", "Find the best matching passages", "knowledge"], ["Cited answer", "Respond with source references", "assistant"], ["Admin review", "Flag uncertainty or missing content", "human"], ["Feedback loop", "Improve approved knowledge", "dashboard"]] },
  "ai-marketing-assistant": { title: "From campaign idea to ready-to-review content", description: "Move from a clear brief to channel-ready drafts without skipping brand review.", steps: [["Campaign goal", "Define the outcome", "input"], ["Audience brief", "Offer, channel and tone", "knowledge"], ["Content ideas", "Explore useful angles", "assistant"], ["Channel variants", "Social, email, landing and ads", "output"], ["Brand check", "Apply claims and voice rules", "decision"], ["Human approval", "Edit and approve before use", "human"], ["Results summary", "Gather channel learnings", "dashboard"]] },
  "ai-calling-appointment-booking": { title: "From contact list to confirmed appointment", description: "Coordinate approved outreach, live availability and reminders with staff routing when needed.", steps: [["Contact selected", "Choose an approved lead or customer", "trigger"], ["Outreach", "Message or approved call flow", "assistant"], ["Intent & timing", "Ask availability and purpose", "input"], ["Calendar check", "Read open appointment slots", "integration"], ["Book or route", "Confirm or involve staff", "human"], ["Reminder", "Send appointment details", "output"], ["Booking report", "Save outcome and summary", "dashboard"]] },
  "ai-workflow-automation": { title: "From manual handoffs to connected daily work", description: "A practical control tower for repetitive work, defined rules and deliberate approvals.", steps: [["Work arrives", "Email, form, CRM or file", "trigger"], ["Extract details", "Read the useful fields", "assistant"], ["Business rules", "Choose the permitted next step", "decision"], ["Approval queue", "Ask a person where required", "human"], ["Tool update", "CRM, sheet, document or email", "integration"], ["Team alert", "Notify the right owner", "output"], ["Task report", "Create an auditable summary", "dashboard"]] },
  "ai-system-integration": { title: "From disconnected tools to one connected AI layer", description: "Map permissions first, connect only approved systems, then monitor real workflows.", steps: [["Tool discovery", "Identify systems already in use", "input"], ["Connection map", "APIs, forms, CRM, files and data", "knowledge"], ["Safe actions", "Define access and permissions", "decision"], ["AI layer", "Connect approved capabilities", "assistant"], ["Test run", "Validate with human approval", "human"], ["Reporting layer", "Add operational visibility", "dashboard"], ["Monitor & improve", "Review quality and exceptions", "output"]] },
}
export function getWorkflow(slug: string) {
  const flow = flows[slug]
  const nodes: WorkflowNodeData[] = flow.steps.map(([label, detail, type], i) => ({ id: `${i + 1}`, label, detail, type, x: i * 225, y: i % 2 ? 125 : 20 }))
  const edges: WorkflowEdgeData[] = nodes.slice(1).map((node, i) => ({ id: `e${i + 1}-${i + 2}`, source: `${i + 1}`, target: node.id }))
  return { title: flow.title, description: flow.description, nodes, edges }
}
