import type { SchemaTypeDefinition } from "sanity"
import { seoFields } from "./objects/seoFields"
import { faqObject } from "./objects/faqObject"
import { ctaObject } from "./objects/ctaObject"
import { workflowNodeObject } from "./objects/workflowNodeObject"
import { workflowEdgeObject } from "./objects/workflowEdgeObject"
import { workflowObject } from "./objects/workflowObject"
import { galleryItemObject } from "./objects/galleryItemObject"
import { servicePage } from "./documents/servicePage"
import { industryPage } from "./documents/industryPage"
import { siteSettings } from "./documents/siteSettings"
import { chatbotKnowledgeItem } from "./documents/chatbotKnowledgeItem"
export const schema: { types: SchemaTypeDefinition[] } = { types: [seoFields, faqObject, ctaObject, workflowNodeObject, workflowEdgeObject, workflowObject, galleryItemObject, servicePage, industryPage, siteSettings, chatbotKnowledgeItem] }
